
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"

def fmt(v, nd=4):
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "N/A"
    return f"{v:.{nd}f}"

def headline_table(df: pd.DataFrame) -> str:
    rows = ["| Dataset | Protocol | Model | Accuracy | F1 | Recall | FPR | False alerts / 10k |",
            "|---|---|---|---|---:|---:|---:|---:|"]
    sub = df[df.protocol.isin(["random-split", "official-split"])]
    for _, r in sub.iterrows():
        rows.append(
            f"| {r.dataset} | {r.protocol} | `{r.model}` | {fmt(r.accuracy)} | "
            f"{fmt(r.f1)} | {fmt(r.recall)} | {fmt(r.fpr)} | "
            f"{fmt(r.false_alerts_per_10k, 1)} |")
    return "\n".join(rows)

def optimism_table(df: pd.DataFrame) -> str:
    rows = ["| Dataset | Model | Random split | Official split | Optimism |",
            "|---|---|---:|---:|---:|"]
    for ds in df.dataset.unique():
        for m in df.model.unique():
            a = df[(df.dataset == ds) & (df.model == m)
                   & (df.protocol == "random-split")]
            b = df[(df.dataset == ds) & (df.model == m)
                   & (df.protocol == "official-split")]
            if len(a) and len(b):
                ga, gb = a.iloc[0].accuracy, b.iloc[0].accuracy
                rows.append(f"| {ds} | `{m}` | {fmt(ga)} | {fmt(gb)} | "
                            f"**+{fmt(ga - gb)}** |")
    return "\n".join(rows)

def novelty_table(df: pd.DataFrame) -> str:
    rows = ["| Dataset | Model | Recall, families seen in training | Recall, families never seen |",
            "|---|---|---:|---:|"]
    sub = df[(df.protocol == "official-split") & df.novel_recall.notna()]
    for _, r in sub.iterrows():
        rows.append(f"| {r.dataset} | `{r.model}` | {fmt(r.known_recall)} | "
                    f"**{fmt(r.novel_recall)}** |")
    return "\n".join(rows) if len(sub) else "_no novel families in this run_"

def operating_points(reports: list[dict]) -> str:
    rows = ["| Dataset | FPR budget | Threshold effect | Recall | Actual FPR | False alerts / 10k |",
            "|---|---|---|---:|---:|---:|"]
    for r in reports:
        if r["protocol"].startswith("official-split@fpr="):
            budget = r["protocol"].split("=")[1]
            rows.append(
                f"| {r['dataset']} | {budget} | `random-forest` | "
                f"{fmt(r['recall'])} | {fmt(r['fpr'])} | "
                f"{fmt(r['false_alerts_per_10k'], 1)} |")
    return "\n".join(rows)

def per_family(reports: list[dict], dataset: str, model="random-forest") -> str:
    for r in reports:
        if (r["dataset"] == dataset and r["model"] == model
                and r["protocol"] == "official-split"):
            fam = r["per_family"]
            rows = ["| Attack family | Flows | Recall | Seen in training? |",
                    "|---|---:|---:|---|"]
            for name, d in sorted(fam.items(),
                                  key=lambda kv: -kv[1]["n"]):
                seen = "no (novel)" if d["novel"] else "yes"
                rows.append(f"| `{name}` | {d['n']:,} | {fmt(d['recall'])} | {seen} |")
            return "\n".join(rows)
    return "_not available_"

def main():
    df = pd.read_csv(RESULTS / "summary.csv")
    reports = json.loads((RESULTS / "reports.json").read_text(encoding="utf-8"))

    parts = [
        "# Results",
        "",
        "Generated by `src/report.py` from `results/summary.csv` and "
        "`results/reports.json`. Do not edit by hand.",
        "",
        "## 1. Headline",
        "", headline_table(df), "",
        "## 2. The optimism of a random split",
        "",
        "Same data, same models, same code: only the partition changes.",
        "", optimism_table(df), "",
        "## 3. Attack families the model was never trained on",
        "", novelty_table(df), "",
        "## 4. Operating points under a false-positive budget",
        "", operating_points(reports), "",
    ]

    for ds in df.dataset.unique():
        parts += [f"## 5. Per-family detection ({ds}, `random-forest`, "
                  f"official split, threshold 0.5)", "",
                  per_family(reports, ds), ""]

    ips_files = sorted(RESULTS.glob("ips-*.json"))
    if ips_files:
        parts += ["## 6. Prevention engine", "",
                  "| Dataset | Flows | Threshold | Recall | Precision | "
                  "False alerts / 10k | Benign flows blocked |",
                  "|---|---:|---:|---:|---:|---:|---:|"]
        for f in ips_files:
            d = json.loads(f.read_text(encoding="utf-8"))
            tp, fp, fn = d["tp"], d["fp"], d["fn"]
            rec = tp / (tp + fn) if tp + fn else 0
            prec = tp / (tp + fp) if tp + fp else 0
            parts.append(
                f"| {d['dataset']} | {d['flows']:,} | "
                f"{d['alert_threshold']:.4f} | {rec:.4f} | {prec:.4f} | "
                f"{10_000*fp/d['flows']:.1f} | {d['blocked_benign']} |")
        parts.append("")

    out = RESULTS / "RESULTS.md"
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out}")

if __name__ == "__main__":
    main()
